jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
          MYSQL_DATABASE: projetoalura_test
        options: >-
          --health-cmd="mysqladmin ping -h localhost --user=root"
          --health-interval=10s
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Wait for MySQL
        run: |
          for i in {30..0}; do
            mysqladmin ping -hmysql --silent && break
            echo "Waiting for MySQL..."
            sleep 1
          done

      - name: Build Project
        run: mvn clean compile

      - name: Run Tests
        run: mvn verify
